#   Copyright (c) 2017, WSO2 Inc. (http://www.wso2.org) All Rights Reserved
#
#   Licensed under the Apache License, Version 2.0 (the \"License\");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an \"AS IS\" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

  # Carbon Configuration Parameters
wso2.carbon:
    # value to uniquely identify a server
  id: carbon-am-key-manager
    # server name
  name: WSO2 AM Key Manager
    # ports used by this server
  ports:
      # port offset
    offset: 0

wso2.securevault:
  secretRepository:
    type: org.wso2.carbon.secvault.repository.DefaultSecretRepository
    parameters:
      privateKeyAlias: wso2carbon
      keystoreLocation: ${sys:carbon.home}/resources/security/securevault.jks
      secretPropertiesFile: ${sys:carbon.home}/conf/${sys:wso2.runtime}/secrets.properties
  masterKeyReader:
    type: org.wso2.carbon.secvault.reader.DefaultMasterKeyReader
    parameters:
      masterKeyReaderFile: ${sys:carbon.home}/conf/${sys:wso2.runtime}/master-keys.yaml

wso2.datasources:
    # datasources
  dataSources:
  - name: WSO2_UM_DB
    description: The datasource used for user management
      # JNDI mapping of a data source
    jndiConfig:
        # JNDI name
        # THIS IS A MANDATORY FIELD
      name: jdbc/WSO2UM_DB
        # JNDI Reference Flag
      useJndiReference: false
      # data source definition
    definition:
        # data source type
        # THIS IS A MANDATORY FIELD
      type: RDBMS
        # data source configuration
      configuration:
        jdbcUrl: 'jdbc:h2:./database/UM_DB;DB_CLOSE_ON_EXIT=FALSE;LOCK_TIMEOUT=60000'
        username: wso2carbon
        password: wso2carbon
        driverClassName: org.h2.Driver
        maxPoolSize: 50
        idleTimeout: 60000
        connectionTestQuery: SELECT 1
        validationTimeout: 30000
        isAutoCommit: false

  - name: WSO2_AUTH_DB
    description: The datasource used for auth features
      # JNDI mapping of a data source
    jndiConfig:
        # JNDI name
        # THIS IS A MANDATORY FIELD
      name: jdbc/WSO2AUTH_DB
        # JNDI Reference Flag
      useJndiReference: false
      # data source definition
    definition:
        # data source type
        # THIS IS A MANDATORY FIELD
      type: RDBMS
        # data source configuration
      configuration:
        jdbcUrl: 'jdbc:h2:./database/AUTH_DB;DB_CLOSE_ON_EXIT=FALSE;LOCK_TIMEOUT=60000'
        username: wso2carbon
        password: wso2carbon
        driverClassName: org.h2.Driver
        maxPoolSize: 50
        idleTimeout: 60000
        connectionTestQuery: SELECT 1
        validationTimeout: 30000
        isAutoCommit: false
