# Configurations for the recommendations sytem - python backend

# Recommendation server hostname and port
host: localhost
port: 8082

# Username and password credentials for the authorization for the server
username: admin
password: admin 

recommendations_count: 5          # Maximum no. of recommendations displayed at the API store
search_details_valid_months: 3    # Search queries before the valid period will be removed
minimum_search_queries: 20        # Search queries are deleted after the validity period only if this minimum no. is available.

# URL to connect to the Mongodb
mongodb_url: localhost:27017/